#Requires -RunAsAdministrator
# ============================================================
#  CPU Userland Spoofer  -  Level A (no kernel driver)
#
#  Userland equivalent of the driver's Track A CPU replay path.
#  Registers a SYSTEM scheduled task that fires at AtStartup +
#  AtLogon and rewrites the string values under
#      HKLM\HARDWARE\DESCRIPTION\System\CentralProcessor\N
#  (ProcessorNameString, Identifier, VendorIdentifier) from
#  profile.cpu.{name_string, identifier, vendor_identifier}.
#
#  Rationale (rev.3, from display-affinity-lab/docs/emac-hwid-recon.md):
#    - EMAC is 100% RegQueryValueEx-based. CPU strings are read
#      exclusively from the HARDWARE hive, NEVER from CPUID directly.
#    - Attributed reader in every capture is RubinOT.exe / rubinot_dx.exe,
#      which only exists post-logon. So a task that fires at logon (before
#      the user launches the game) covers the entire attack surface EMAC
#      observes today.
#    - HARDWARE hive is VOLATILE - kernel repopulates it from CPUID on
#      every cold boot. That is why the task also fires AtStartup: we
#      overwrite the fresh values before winlogon completes.
#
#  Trade-offs vs kernel driver Track A (spoof-smbios.ps1 -CpuOnly):
#    - PLUS: no kernel driver required. No WDAC / testsigning / signed
#      cert. Works on Level A boxes where user refuses to install rstflt.
#    - MINUS: race window. Anti-cheats that read CentralProcessor\* from
#      a service that starts before Winlogon (nothing observed today, but
#      possible tomorrow) can catch the un-spoofed values. For guaranteed
#      pre-EMAC application on such a threat model, use Level C driver.
#    - MINUS: only string values are rewritten. Numeric values
#      (~MHz, FeatureSet, CPUID leaves cached by kernel) come from CPUID
#      and stay real. Anti-cheats that cross-check them against CPUID
#      would see the mismatch. This matches the driver's behavior - both
#      paths rewrite strings only, by design.
#
#  Modes:
#    -Apply     (default)  Register the task + write helper script
#    -Show                 Show current task state + registry values
#    -RunNow               Run the helper script action once (test)
#    -Uninstall            Unregister the task (values regenerate at
#                          next cold boot from CPUID; no restore needed)
#    -DryRun               Preview what would be written; no changes
# ============================================================

param(
    [switch]$Apply,
    [switch]$Show,
    [switch]$RunNow,
    [switch]$Uninstall,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

. "$PSScriptRoot\_ui-common.ps1"

# ============================================================
#  Constants
# ============================================================
$ProfileDir       = "C:\ProgramData\.hwcfg"
$ProfilePath      = Join-Path $ProfileDir "profile.json"
$TaskHelperPath   = Join-Path $ProfileDir "SpoofCPU-Task.ps1"
$TaskName         = "SpoofCPUUserland"
$TaskFolder       = "\HWToolkit\"
$TaskFullPath     = "$TaskFolder$TaskName"
$EventLogSource   = "HWToolkit-CPUSpoof"
$EventLogChannel  = "Application"
$CpuRegRoot       = "HKLM:\HARDWARE\DESCRIPTION\System\CentralProcessor"

# ============================================================
#  Mode dispatch: mutual exclusion
# ============================================================
$modeCount = 0
if ($Apply)     { $modeCount++ }
if ($Show)      { $modeCount++ }
if ($RunNow)    { $modeCount++ }
if ($Uninstall) { $modeCount++ }
if ($modeCount -gt 1) {
    Write-Err "Modos -Apply / -Show / -RunNow / -Uninstall sao mutuamente exclusivos."
    exit 1
}
# Default para -Apply se nada especificado
if ($modeCount -eq 0) { $Apply = $true }

# ============================================================
#  Helper script content
#
#  This block is what gets written to $TaskHelperPath and executed
#  by the scheduled task action. It runs as SYSTEM with no console.
#
#  Design constraints:
#    - Silent on missing profile (task should not spam Event Log on
#      unarmed boxes where the toolkit was uninstalled).
#    - Log only anomalies + one summary entry per run (event ID 1000).
#      That way check-consistency.ps1 can grep the log for evidence.
#    - No exception must escape: task must never show FAILED in Task
#      Scheduler even if profile is malformed. exit 0 always.
#    - ASCII-only. No em-dashes, no accents.
# ============================================================
$TaskHelperScript = @'
# HWToolkit-CPUSpoof task helper (auto-generated by spoof-cpu-userland.ps1)
# Runs as SYSTEM at AtStartup + AtLogon. Rewrites CentralProcessor\N
# string values from C:\ProgramData\.hwcfg\profile.json (cpu block).

$ErrorActionPreference = "Continue"

$profilePath = "C:\ProgramData\.hwcfg\profile.json"
$cpuRegRoot  = "HKLM:\HARDWARE\DESCRIPTION\System\CentralProcessor"
$logSource   = "HWToolkit-CPUSpoof"
$logChannel  = "Application"

function Write-SpoofLog {
    param([string]$Level, [int]$EventId, [string]$Message)
    try {
        if (-not [System.Diagnostics.EventLog]::SourceExists($logSource)) {
            [System.Diagnostics.EventLog]::CreateEventSource($logSource, $logChannel)
        }
        Write-EventLog -LogName $logChannel -Source $logSource `
            -EntryType $Level -EventId $EventId -Message $Message
    } catch {
        # Se o Event Log falhar, silencia - task nao pode quebrar por causa disso.
    }
}

if (-not (Test-Path $profilePath)) {
    # Profile ausente = toolkit desinstalado. Nao logar (silencio proposital).
    exit 0
}

try {
    $prof = Get-Content $profilePath -Raw -ErrorAction Stop | ConvertFrom-Json
} catch {
    Write-SpoofLog -Level Warning -EventId 2001 `
        -Message "profile.json ilegivel; spoof nao aplicado. Erro: $_"
    exit 0
}

if (-not ($prof.PSObject.Properties.Name -contains "cpu") -or -not $prof.cpu) {
    Write-SpoofLog -Level Warning -EventId 2002 `
        -Message "profile.json sem bloco cpu (v< 9); spoof nao aplicado."
    exit 0
}

$cpuName   = [string]$prof.cpu.name_string
$cpuIdent  = [string]$prof.cpu.identifier
$cpuVendor = [string]$prof.cpu.vendor_identifier

if ([string]::IsNullOrWhiteSpace($cpuName) -or `
    [string]::IsNullOrWhiteSpace($cpuIdent) -or `
    [string]::IsNullOrWhiteSpace($cpuVendor)) {
    Write-SpoofLog -Level Warning -EventId 2003 `
        -Message "profile.cpu tem campos vazios; spoof nao aplicado."
    exit 0
}

# Enumera subkeys 0..N sob CentralProcessor (uma por logical processor).
$cpuKeys = @()
try {
    $cpuKeys = Get-ChildItem -Path $cpuRegRoot -ErrorAction Stop
} catch {
    Write-SpoofLog -Level Error -EventId 3001 `
        -Message "Falha ao enumerar CentralProcessor\*: $_"
    exit 0
}

$patched   = 0
$failed    = 0
foreach ($key in $cpuKeys) {
    $p = $key.PSPath
    try {
        Set-ItemProperty -Path $p -Name "ProcessorNameString" -Value $cpuName   -Type String -Force -ErrorAction Stop
        Set-ItemProperty -Path $p -Name "Identifier"          -Value $cpuIdent  -Type String -Force -ErrorAction Stop
        Set-ItemProperty -Path $p -Name "VendorIdentifier"    -Value $cpuVendor -Type String -Force -ErrorAction Stop
        $patched++
    } catch {
        $failed++
        Write-SpoofLog -Level Warning -EventId 2010 `
            -Message "Falha ao escrever em $($key.PSChildName): $_"
    }
}

$msg = "CPU spoof aplicado: $patched cores patched, $failed falharam. " +
       "name_string='$cpuName' vendor='$cpuVendor'"
Write-SpoofLog -Level Information -EventId 1000 -Message $msg

exit 0
'@

# ============================================================
#  Helper: garante Event Log source existe (nao-fatal)
# ============================================================
function Ensure-EventLogSource {
    try {
        if (-not [System.Diagnostics.EventLog]::SourceExists($EventLogSource)) {
            [System.Diagnostics.EventLog]::CreateEventSource($EventLogSource, $EventLogChannel)
            Write-OK "Event log source '$EventLogSource' criado no canal $EventLogChannel"
        } else {
            Write-Info "Event log source '$EventLogSource' ja existe"
        }
    } catch {
        Write-Warn "Falha ao criar Event Log source: $_"
        Write-Warn "Task continuara funcionando; logs so nao aparecerao."
    }
}

# ============================================================
#  Helper: le e valida profile.cpu
# ============================================================
function Get-CpuProfile {
    if (-not (Test-Path $ProfilePath)) {
        Write-Err "Profile nao encontrado em $ProfilePath"
        Write-Err "Rode primeiro:  .\generate-profile.ps1 -Generate"
        return $null
    }
    try {
        $p = Get-Content $ProfilePath -Raw | ConvertFrom-Json
    } catch {
        Write-Err "profile.json ilegivel: $_"
        return $null
    }
    if (-not ($p.PSObject.Properties.Name -contains "cpu") -or -not $p.cpu) {
        Write-Err "Profile sem bloco 'cpu' (v< 9). Regenere com generate-profile.ps1."
        return $null
    }
    $required = @("name_string","identifier","vendor_identifier")
    foreach ($f in $required) {
        $val = $p.cpu.$f
        if ([string]::IsNullOrWhiteSpace([string]$val)) {
            Write-Err "profile.cpu.$f ausente ou vazio."
            return $null
        }
    }
    return $p.cpu
}

# ============================================================
#  Uninstall mode
# ============================================================
if ($Uninstall) {
    Write-Section "Removendo task HWToolkit\$TaskName"

    $existing = Get-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        if ($DryRun) {
            Write-Info "[DryRun] Unregister-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName"
        } else {
            Unregister-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -Confirm:$false -ErrorAction Stop
            Write-OK "Task removida"
        }
    } else {
        Write-Info "Task nao registrada; nada a remover"
    }

    if (Test-Path $TaskHelperPath) {
        if ($DryRun) {
            Write-Info "[DryRun] Remove-Item $TaskHelperPath"
        } else {
            Remove-Item -Path $TaskHelperPath -Force -ErrorAction SilentlyContinue
            Write-OK "Helper script removido"
        }
    } else {
        Write-Info "Helper script ja ausente"
    }

    Write-Host ""
    Write-Warn "NOTA: valores em CentralProcessor\* NAO sao restaurados aqui."
    Write-Warn "O HARDWARE hive e volatile e o kernel repopula do CPUID no"
    Write-Warn "proximo cold boot. Reboot para voltar aos valores reais."
    Write-Host ""
    exit 0
}

# ============================================================
#  Show mode
# ============================================================
if ($Show) {
    Write-Section "Task"
    $existing = Get-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Write-OK "Registrada: $TaskFullPath"
        Write-Info "  State: $($existing.State)"
        foreach ($t in $existing.Triggers) {
            Write-Info "  Trigger: $($t.CimClass.CimClassName)"
        }
        try {
            $info = Get-ScheduledTaskInfo -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction Stop
            Write-Info "  LastRunTime:     $($info.LastRunTime)"
            Write-Info "  LastTaskResult:  0x$('{0:X8}' -f $info.LastTaskResult)"
            Write-Info "  NextRunTime:     $($info.NextRunTime)"
        } catch {
            Write-Warn "Get-ScheduledTaskInfo falhou: $_"
        }
    } else {
        Write-Warn "Task NAO registrada"
    }

    Write-Section "Helper script"
    if (Test-Path $TaskHelperPath) {
        $fi = Get-Item $TaskHelperPath
        Write-OK "Existe: $TaskHelperPath ($($fi.Length) bytes, escrito em $($fi.LastWriteTime))"
    } else {
        Write-Warn "Helper script ausente: $TaskHelperPath"
    }

    Write-Section "Registro CentralProcessor atual"
    try {
        $cpuKeys = Get-ChildItem -Path $CpuRegRoot -ErrorAction Stop | Sort-Object PSChildName
        foreach ($k in $cpuKeys) {
            $p = Get-ItemProperty -Path $k.PSPath -ErrorAction SilentlyContinue
            Write-Info "  [$($k.PSChildName)] Name='$($p.ProcessorNameString)'"
            Write-Info "        Vendor='$($p.VendorIdentifier)' Ident='$($p.Identifier)'"
        }
    } catch {
        Write-Warn "Falha ao ler CentralProcessor: $_"
    }

    Write-Section "Ultimos eventos ($EventLogSource)"
    try {
        $ev = Get-WinEvent -LogName $EventLogChannel -MaxEvents 5 -FilterXPath "*[System[Provider[@Name='$EventLogSource']]]" -ErrorAction Stop
        foreach ($e in $ev) {
            Write-Info "  $($e.TimeCreated) EID=$($e.Id) $($e.LevelDisplayName): $($e.Message)"
        }
    } catch {
        Write-Warn "Sem eventos ainda (ou source nao existe)"
    }

    exit 0
}

# ============================================================
#  Apply mode (default)  +  RunNow shares most of the setup
# ============================================================
Write-Host ""
Write-Host "  ============================================" -ForegroundColor Cyan
Write-Host "    CPU Userland Spoofer  (Level A / no driver)" -ForegroundColor Cyan
Write-Host "  ============================================" -ForegroundColor Cyan
Write-Host ""

# ------ Step 1: validar profile ------
Write-Section "Profile"
$cpu = Get-CpuProfile
if (-not $cpu) { exit 1 }

Write-OK "profile.cpu carregado"
Write-Info "  name_string:       $($cpu.name_string)"
Write-Info "  identifier:        $($cpu.identifier)"
Write-Info "  vendor_identifier: $($cpu.vendor_identifier)"

# ------ Step 2: escrever helper script ------
Write-Section "Helper script"
if (-not (Test-Path $ProfileDir)) {
    if ($DryRun) {
        Write-Info "[DryRun] New-Item -Path $ProfileDir -ItemType Directory"
    } else {
        New-Item -Path $ProfileDir -ItemType Directory -Force | Out-Null
        Write-OK "Criado $ProfileDir"
    }
}

if ($DryRun) {
    Write-Info "[DryRun] Escreveria helper em $TaskHelperPath ($($TaskHelperScript.Length) bytes)"
} else {
    # Escrita atomica: .tmp -> Move-Item -Force (padrao da casa).
    $tmp = "$TaskHelperPath.tmp"
    Set-Content -Path $tmp -Value $TaskHelperScript -Encoding ASCII -Force
    Move-Item -Path $tmp -Destination $TaskHelperPath -Force
    Write-OK "Helper escrito: $TaskHelperPath"
}

# ------ Step 3: garantir Event Log source ------
Write-Section "Event Log source"
if ($DryRun) {
    Write-Info "[DryRun] Ensure-EventLogSource ($EventLogSource -> $EventLogChannel)"
} else {
    Ensure-EventLogSource
}

# ------ Step 4: registrar task (a menos que seja RunNow-only) ------
if (-not $RunNow) {
    Write-Section "Task"

    $existing = Get-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        if ($DryRun) {
            Write-Info "[DryRun] Unregister-ScheduledTask (task ja existe, seria substituida)"
        } else {
            Unregister-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
            Write-Info "Task existente removida (sera recriada)"
        }
    }

    $psArgs = "-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$TaskHelperPath`""
    $action    = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $psArgs
    $trigStart = New-ScheduledTaskTrigger -AtStartup
    $trigLogon = New-ScheduledTaskTrigger -AtLogOn
    $settings  = New-ScheduledTaskSettingsSet `
                    -AllowStartIfOnBatteries `
                    -DontStopIfGoingOnBatteries `
                    -StartWhenAvailable `
                    -ExecutionTimeLimit ([TimeSpan]::FromMinutes(2))
    $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest

    if ($DryRun) {
        Write-Info "[DryRun] Register-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName"
        Write-Info "         Action:   powershell.exe $psArgs"
        Write-Info "         Trigger:  AtStartup + AtLogOn"
        Write-Info "         Principal: SYSTEM / Highest"
    } else {
        Register-ScheduledTask `
            -TaskPath $TaskFolder `
            -TaskName $TaskName `
            -Action $action `
            -Trigger @($trigStart, $trigLogon) `
            -Settings $settings `
            -Principal $principal `
            -Force | Out-Null
        Write-OK "Task registrada: $TaskFullPath (SYSTEM, AtStartup + AtLogOn)"
    }
}

# ------ Step 5: RunNow (opcional) ------
if ($RunNow) {
    Write-Section "RunNow"
    if ($DryRun) {
        Write-Info "[DryRun] Executaria: powershell.exe -File $TaskHelperPath"
    } else {
        # Se a task existir, use Start-ScheduledTask (mesmo contexto SYSTEM da task real).
        # Se nao existir (apply nao rodou ainda ou RunNow-only), roda inline como o
        # processo atual (ja Admin) - nao e SYSTEM mas o efeito no HKLM e identico.
        $existing = Get-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction SilentlyContinue
        if ($existing) {
            Start-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName
            Write-OK "Task disparada via Start-ScheduledTask"
            Start-Sleep -Seconds 2
            try {
                $info = Get-ScheduledTaskInfo -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction Stop
                Write-Info "  LastTaskResult: 0x$('{0:X8}' -f $info.LastTaskResult)"
                Write-Info "  LastRunTime:    $($info.LastRunTime)"
            } catch { }
        } else {
            Write-Info "Task nao registrada - executando helper inline (contexto Admin, nao SYSTEM)"
            & powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $TaskHelperPath
            Write-OK "Helper executado inline"
        }
    }
}

# ------ Step 6: snapshot pos-arm ------
Write-Section "Registro CentralProcessor pos-arm"
try {
    $cpuKeys = Get-ChildItem -Path $CpuRegRoot -ErrorAction Stop | Sort-Object PSChildName
    foreach ($k in $cpuKeys) {
        $p = Get-ItemProperty -Path $k.PSPath -ErrorAction SilentlyContinue
        Write-Info "  [$($k.PSChildName)] Name='$($p.ProcessorNameString)'"
        Write-Info "        Vendor='$($p.VendorIdentifier)' Ident='$($p.Identifier)'"
    }
} catch {
    Write-Warn "Falha ao ler CentralProcessor: $_"
}

# ============================================================
#  Resumo + race-window disclosure
# ============================================================
Write-Host ""
Write-Host "  ============================================" -ForegroundColor Green
Write-Host "    CONCLUIDO!" -ForegroundColor Green
Write-Host "  ============================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Task '$TaskName' registrada em '$TaskFolder' como SYSTEM." -ForegroundColor White
Write-Host "  Triggers: AtStartup + AtLogOn." -ForegroundColor White
Write-Host ""
Write-Host "  Race window (leia antes de rodar RubinOT):" -ForegroundColor Yellow
Write-Host "    - Trigger AtLogOn dispara APOS winlogon completar." -ForegroundColor Yellow
Write-Host "    - Se voce lancar RubinOT.exe antes disso (~2s pos-logon)," -ForegroundColor Yellow
Write-Host "      as strings ainda estarao originais no primeiro read." -ForegroundColor Yellow
Write-Host "    - Espere pelo evento EID 1000 no Event Log '$EventLogChannel'" -ForegroundColor Yellow
Write-Host "      (source $EventLogSource) antes de lancar o jogo." -ForegroundColor Yellow
Write-Host "    - Para eliminar a race, instale o driver (Level C):" -ForegroundColor Yellow
Write-Host "      .\03-instalar-driver.bat + .\scripts\spoof-smbios.ps1 -CpuOnly" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Verificar estado:  .\scripts\spoof-cpu-userland.ps1 -Show" -ForegroundColor White
Write-Host "  Testar agora:      .\scripts\spoof-cpu-userland.ps1 -RunNow" -ForegroundColor White
Write-Host "  Desinstalar:       .\scripts\spoof-cpu-userland.ps1 -Uninstall" -ForegroundColor White
Write-Host ""

exit 0
