#Requires -RunAsAdministrator
# ============================================================
#  Spoof Persistence Task  -  Level A (no kernel driver)
#
#  Registers a SYSTEM scheduled task that re-arms userland
#  spoofers whose registry cache is reverted by Windows PnP
#  or display driver on every boot:
#
#    - spoof-pci-hardwareid.ps1
#        PnP re-reads SUBSYS/DevID from PCI config space when
#        the bus driver enumerates devices at boot.
#    - spoof-edid-full.ps1
#        The display miniport re-reads EDID over DDC/I2C when
#        the monitor arbitrator attaches, wiping any prior
#        HKLM\...\Device Parameters\EDID override.
#
#  This task DOES NOT touch CPU or MachineGuid persistence -
#  those are covered by spoof-cpu-userland.ps1 and the one-shot
#  writes done by 04b-aplicar-hwid-emac.bat respectively.
#
#  Race window (same reasoning as spoof-cpu-userland.ps1):
#    - AtStartup fires BEFORE PnP finishes device init. If our
#      re-arm lands first, PnP overwrites us seconds later.
#    - AtLogOn fires AFTER winlogon, which is after most PnP
#      init has settled. This is the PRIMARY reliable trigger.
#    - Kept AtStartup as a fallback for boxes that sit on the
#      lock screen for extended periods without logon.
#    - Optional -LogonDelay adds a 1-minute delay after logon
#      so PnP fully settles before we write. Recommended.
#
#  Trade-offs vs kernel driver approach:
#    - PLUS: no signed kernel driver, no WDAC / testsigning.
#    - MINUS: race window (see above). Anti-cheats that read
#      PCI SUBSYS or EDID from a boot-start service can catch
#      the pre-spoof values on the first boot after logon
#      trigger fires.
#    - MINUS: EDID persistence on Hyper-V VMs is inert - the
#      synthetic display driver re-reads from the host on every
#      reboot and ignores registry override. Real hardware
#      only. This is a known VM limitation.
#
#  Modes:
#    -Apply     (default)  Register the task + write helper script
#    -Show                 Show current task state + last events
#    -RunNow               Run the helper script action once
#    -Uninstall            Unregister the task + remove helper
#    -DryRun               Preview what would be written
#
#  Optional flags:
#    -RepoPath <path>      Override toolkit repo root
#                          (default: C:\Users\xyrlan\hwtoolkit)
#    -LogonDelay           Add PT1M delay after AtLogOn trigger
#                          so PnP/display driver settles first.
# ============================================================

param(
    [switch]$Apply,
    [switch]$Show,
    [switch]$RunNow,
    [switch]$Uninstall,
    [switch]$DryRun,
    [string]$RepoPath = "C:\Users\xyrlan\hwtoolkit",
    [switch]$LogonDelay
)

$ErrorActionPreference = "Stop"

. "$PSScriptRoot\_ui-common.ps1"

# ============================================================
#  Constants
# ============================================================
$ProfileDir       = "C:\ProgramData\.hwcfg"
$ProfilePath      = Join-Path $ProfileDir "profile.json"
$TaskHelperPath   = Join-Path $ProfileDir "SpoofPersistence-Task.ps1"
$TaskName         = "SpoofPersistence"
$TaskFolder       = "\HWToolkit\"
$TaskFullPath     = "$TaskFolder$TaskName"
$EventLogSource   = "HWToolkit-Persistence"
$EventLogChannel  = "Application"

# Normalize RepoPath: strip trailing slash if any.
$RepoPath = $RepoPath.TrimEnd('\').TrimEnd('/')
$ScriptsDir = Join-Path $RepoPath "scripts"

# ============================================================
#  Mode dispatch: mutual exclusion
# ============================================================
$modeCount = 0
if ($Apply)     { $modeCount++ }
if ($Show)      { $modeCount++ }
if ($RunNow)    { $modeCount++ }
if ($Uninstall) { $modeCount++ }
if ($modeCount -gt 1) {
    Write-Err "Modos -Apply / -Show / -RunNow / -Uninstall sao mutuamente exclusivos."
    exit 1
}
# Default para -Apply se nada especificado
if ($modeCount -eq 0) { $Apply = $true }

# ============================================================
#  Helper script content template
#
#  The two placeholders __SCRIPTS_DIR__ get replaced with the
#  effective ScriptsDir path before the file is written. That
#  way the helper on disk has an absolute, hardcoded path and
#  runs with zero dependency on env / cwd / PSScriptRoot.
#
#  Design constraints (same as spoof-cpu-userland helper):
#    - Silent on missing profile (unarmed box = no log spam).
#    - Silent on missing spoofer scripts (graceful degrade -
#      user may have moved/removed the repo but left the task).
#    - exit 0 always so Task Scheduler shows Success.
#    - ASCII-only.
# ============================================================
$TaskHelperTemplate = @'
# HWToolkit-Persistence task helper
# Auto-generated by spoof-persistence-task.ps1
# Runs as SYSTEM at AtStartup + AtLogOn. Re-arms PCI hardwareid
# and EDID spoofers whose registry cache gets reverted by PnP /
# display driver on boot.

$ErrorActionPreference = "Continue"

$profilePath = "C:\ProgramData\.hwcfg\profile.json"
$scriptsDir  = "__SCRIPTS_DIR__"
$pciScript   = Join-Path $scriptsDir "spoof-pci-hardwareid.ps1"
$edidScript  = Join-Path $scriptsDir "spoof-edid-full.ps1"
$logSource   = "HWToolkit-Persistence"
$logChannel  = "Application"

function Write-SpoofLog {
    param([string]$Level, [int]$EventId, [string]$Message)
    try {
        if (-not [System.Diagnostics.EventLog]::SourceExists($logSource)) {
            [System.Diagnostics.EventLog]::CreateEventSource($logSource, $logChannel)
        }
        Write-EventLog -LogName $logChannel -Source $logSource `
            -EntryType $Level -EventId $EventId -Message $Message
    } catch {
        # Se o Event Log falhar, silencia - task nao pode quebrar por causa disso.
    }
}

# Profile ausente = toolkit desinstalado. Nao logar (silencio proposital).
if (-not (Test-Path $profilePath)) {
    exit 0
}

$pciExit  = "SKIP"
$edidExit = "SKIP"

# --- Re-arm PCI hardwareid ---
if (Test-Path $pciScript) {
    try {
        & powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass `
            -File $pciScript *>$null
        $pciExit = "$LASTEXITCODE"
    } catch {
        $pciExit = "ERR"
        Write-SpoofLog -Level Warning -EventId 2010 `
            -Message "Falha ao invocar spoof-pci-hardwareid.ps1: $_"
    }
} else {
    Write-SpoofLog -Level Warning -EventId 2020 `
        -Message "Script ausente (skip PCI): $pciScript"
}

# --- Re-arm EDID ---
if (Test-Path $edidScript) {
    try {
        & powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass `
            -File $edidScript *>$null
        $edidExit = "$LASTEXITCODE"
    } catch {
        $edidExit = "ERR"
        Write-SpoofLog -Level Warning -EventId 2011 `
            -Message "Falha ao invocar spoof-edid-full.ps1: $_"
    }
} else {
    Write-SpoofLog -Level Warning -EventId 2021 `
        -Message "Script ausente (skip EDID): $edidScript"
}

Write-SpoofLog -Level Information -EventId 2000 `
    -Message "Persistence re-armed: pci=$pciExit edid=$edidExit"

exit 0
'@

$TaskHelperScript = $TaskHelperTemplate.Replace('__SCRIPTS_DIR__', $ScriptsDir)

# ============================================================
#  Helper: garante Event Log source existe (nao-fatal)
# ============================================================
function Ensure-EventLogSource {
    try {
        if (-not [System.Diagnostics.EventLog]::SourceExists($EventLogSource)) {
            [System.Diagnostics.EventLog]::CreateEventSource($EventLogSource, $EventLogChannel)
            Write-OK "Event log source '$EventLogSource' criado no canal $EventLogChannel"
        } else {
            Write-Info "Event log source '$EventLogSource' ja existe"
        }
    } catch {
        Write-Warn "Falha ao criar Event Log source: $_"
        Write-Warn "Task continuara funcionando; logs so nao aparecerao."
    }
}

# ============================================================
#  Uninstall mode
# ============================================================
if ($Uninstall) {
    Write-Section "Removendo task HWToolkit\$TaskName"

    $existing = Get-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        if ($DryRun) {
            Write-Info "[DryRun] Unregister-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName"
        } else {
            Unregister-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -Confirm:$false -ErrorAction Stop
            Write-OK "Task removida"
        }
    } else {
        Write-Info "Task nao registrada; nada a remover"
    }

    if (Test-Path $TaskHelperPath) {
        if ($DryRun) {
            Write-Info "[DryRun] Remove-Item $TaskHelperPath"
        } else {
            Remove-Item -Path $TaskHelperPath -Force -ErrorAction SilentlyContinue
            Write-OK "Helper script removido"
        }
    } else {
        Write-Info "Helper script ja ausente"
    }

    Write-Host ""
    Write-Warn "NOTA: valores atuais em PCI\...\Device Parameters e"
    Write-Warn "monitor EDID NAO sao restaurados aqui. Rode"
    Write-Warn "08b-rollback-userland.bat para reverter dos backups .hwcfg."
    Write-Host ""
    exit 0
}

# ============================================================
#  Show mode
# ============================================================
if ($Show) {
    Write-Section "Task"
    $existing = Get-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Write-OK "Registrada: $TaskFullPath"
        Write-Info "  State: $($existing.State)"
        foreach ($t in $existing.Triggers) {
            Write-Info "  Trigger: $($t.CimClass.CimClassName)"
        }
        try {
            $info = Get-ScheduledTaskInfo -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction Stop
            Write-Info "  LastRunTime:     $($info.LastRunTime)"
            Write-Info "  LastTaskResult:  0x$('{0:X8}' -f $info.LastTaskResult)"
            Write-Info "  NextRunTime:     $($info.NextRunTime)"
        } catch {
            Write-Warn "Get-ScheduledTaskInfo falhou: $_"
        }
    } else {
        Write-Warn "Task NAO registrada"
    }

    Write-Section "Helper script"
    if (Test-Path $TaskHelperPath) {
        $fi = Get-Item $TaskHelperPath
        Write-OK "Existe: $TaskHelperPath ($($fi.Length) bytes, escrito em $($fi.LastWriteTime))"
    } else {
        Write-Warn "Helper script ausente: $TaskHelperPath"
    }

    Write-Section "Spoofers referenciados"
    $pciScript  = Join-Path $ScriptsDir "spoof-pci-hardwareid.ps1"
    $edidScript = Join-Path $ScriptsDir "spoof-edid-full.ps1"
    if (Test-Path $pciScript)  { Write-OK  "PCI  spoofer:  $pciScript"  } else { Write-Warn "PCI  spoofer AUSENTE: $pciScript" }
    if (Test-Path $edidScript) { Write-OK  "EDID spoofer: $edidScript" } else { Write-Warn "EDID spoofer AUSENTE: $edidScript" }

    Write-Section "Ultimos eventos ($EventLogSource)"
    try {
        $ev = Get-WinEvent -LogName $EventLogChannel -MaxEvents 5 -FilterXPath "*[System[Provider[@Name='$EventLogSource']]]" -ErrorAction Stop
        foreach ($e in $ev) {
            Write-Info "  $($e.TimeCreated) EID=$($e.Id) $($e.LevelDisplayName): $($e.Message)"
        }
    } catch {
        Write-Warn "Sem eventos ainda (ou source nao existe)"
    }

    exit 0
}

# ============================================================
#  Apply mode (default)  +  RunNow shares most of the setup
# ============================================================
Write-Host ""
Write-Host "  ============================================" -ForegroundColor Cyan
Write-Host "    Spoof Persistence Task  (Level A / no driver)" -ForegroundColor Cyan
Write-Host "  ============================================" -ForegroundColor Cyan
Write-Host ""

# ------ Step 1: sanity-check repo/scripts ------
Write-Section "Repo"
Write-Info "  RepoPath:   $RepoPath"
Write-Info "  ScriptsDir: $ScriptsDir"

$pciScript  = Join-Path $ScriptsDir "spoof-pci-hardwareid.ps1"
$edidScript = Join-Path $ScriptsDir "spoof-edid-full.ps1"

if (Test-Path $pciScript) {
    Write-OK "PCI  spoofer encontrado: $pciScript"
} else {
    Write-Warn "PCI  spoofer AUSENTE: $pciScript (task ainda sera criada; helper degrade graciosamente)"
}
if (Test-Path $edidScript) {
    Write-OK "EDID spoofer encontrado: $edidScript"
} else {
    Write-Warn "EDID spoofer AUSENTE: $edidScript (task ainda sera criada; helper degrade graciosamente)"
}

# ------ Step 2: escrever helper script ------
Write-Section "Helper script"
if (-not (Test-Path $ProfileDir)) {
    if ($DryRun) {
        Write-Info "[DryRun] New-Item -Path $ProfileDir -ItemType Directory"
    } else {
        New-Item -Path $ProfileDir -ItemType Directory -Force | Out-Null
        Write-OK "Criado $ProfileDir"
    }
}

if ($DryRun) {
    Write-Info "[DryRun] Escreveria helper em $TaskHelperPath ($($TaskHelperScript.Length) bytes)"
} else {
    # Escrita atomica: .tmp -> Move-Item -Force (padrao da casa).
    $tmp = "$TaskHelperPath.tmp"
    Set-Content -Path $tmp -Value $TaskHelperScript -Encoding ASCII -Force
    Move-Item -Path $tmp -Destination $TaskHelperPath -Force
    Write-OK "Helper escrito: $TaskHelperPath"
}

# ------ Step 3: garantir Event Log source ------
Write-Section "Event Log source"
if ($DryRun) {
    Write-Info "[DryRun] Ensure-EventLogSource ($EventLogSource -> $EventLogChannel)"
} else {
    Ensure-EventLogSource
}

# ------ Step 4: registrar task (a menos que seja RunNow-only) ------
if (-not $RunNow) {
    Write-Section "Task"

    $existing = Get-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        if ($DryRun) {
            Write-Info "[DryRun] Unregister-ScheduledTask (task ja existe, seria substituida)"
        } else {
            Unregister-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
            Write-Info "Task existente removida (sera recriada)"
        }
    }

    $psArgs = "-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$TaskHelperPath`""
    $action    = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $psArgs

    # AtStartup fallback trigger (fires before PnP settles; may be no-op if PnP overwrites us later).
    $trigStart = New-ScheduledTaskTrigger -AtStartup

    # AtLogOn primary trigger. Optional 1-minute delay so PnP / display driver fully settle
    # before we write - otherwise the write races with device init and gets overwritten.
    if ($LogonDelay) {
        $trigLogon = New-ScheduledTaskTrigger -AtLogOn
        $trigLogon.Delay = "PT1M"
    } else {
        $trigLogon = New-ScheduledTaskTrigger -AtLogOn
    }

    $settings  = New-ScheduledTaskSettingsSet `
                    -AllowStartIfOnBatteries `
                    -DontStopIfGoingOnBatteries `
                    -StartWhenAvailable `
                    -ExecutionTimeLimit ([TimeSpan]::FromMinutes(3))
    $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest

    if ($DryRun) {
        Write-Info "[DryRun] Register-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName"
        Write-Info "         Action:    powershell.exe $psArgs"
        if ($LogonDelay) {
            Write-Info "         Trigger:   AtStartup + AtLogOn (Delay=PT1M)"
        } else {
            Write-Info "         Trigger:   AtStartup + AtLogOn"
        }
        Write-Info "         Principal: SYSTEM / Highest"
    } else {
        Register-ScheduledTask `
            -TaskPath $TaskFolder `
            -TaskName $TaskName `
            -Action $action `
            -Trigger @($trigStart, $trigLogon) `
            -Settings $settings `
            -Principal $principal `
            -Force | Out-Null
        if ($LogonDelay) {
            Write-OK "Task registrada: $TaskFullPath (SYSTEM, AtStartup + AtLogOn+PT1M)"
        } else {
            Write-OK "Task registrada: $TaskFullPath (SYSTEM, AtStartup + AtLogOn)"
        }
    }
}

# ------ Step 5: RunNow (opcional) ------
if ($RunNow) {
    Write-Section "RunNow"
    if ($DryRun) {
        Write-Info "[DryRun] Executaria: powershell.exe -File $TaskHelperPath"
    } else {
        $existing = Get-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction SilentlyContinue
        if ($existing) {
            Start-ScheduledTask -TaskPath $TaskFolder -TaskName $TaskName
            Write-OK "Task disparada via Start-ScheduledTask"
            Start-Sleep -Seconds 2
            try {
                $info = Get-ScheduledTaskInfo -TaskPath $TaskFolder -TaskName $TaskName -ErrorAction Stop
                Write-Info "  LastTaskResult: 0x$('{0:X8}' -f $info.LastTaskResult)"
                Write-Info "  LastRunTime:    $($info.LastRunTime)"
            } catch { }
        } else {
            Write-Info "Task nao registrada - executando helper inline (contexto Admin, nao SYSTEM)"
            & powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $TaskHelperPath
            Write-OK "Helper executado inline"
        }
    }
}

# ============================================================
#  Resumo + race-window disclosure
# ============================================================
Write-Host ""
Write-Host "  ============================================" -ForegroundColor Green
Write-Host "    CONCLUIDO!" -ForegroundColor Green
Write-Host "  ============================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Task '$TaskName' registrada em '$TaskFolder' como SYSTEM." -ForegroundColor White
if ($LogonDelay) {
    Write-Host "  Triggers: AtStartup + AtLogOn (delay 1min)." -ForegroundColor White
} else {
    Write-Host "  Triggers: AtStartup + AtLogOn." -ForegroundColor White
}
Write-Host ""
Write-Host "  Race window (leia antes de rodar RubinOT):" -ForegroundColor Yellow
Write-Host "    - AtStartup dispara ANTES do PnP terminar - o re-arm" -ForegroundColor Yellow
Write-Host "      pode ser sobrescrito pela init de dispositivos que vem depois." -ForegroundColor Yellow
Write-Host "    - AtLogOn dispara APOS winlogon = apos maior parte da init PnP." -ForegroundColor Yellow
Write-Host "      Este e o trigger confiavel; AtStartup e so fallback." -ForegroundColor Yellow
Write-Host "    - Se nao passou -LogonDelay, considere re-aplicar com" -ForegroundColor Yellow
Write-Host "      -LogonDelay para adicionar 1 minuto pos-logon antes do write." -ForegroundColor Yellow
Write-Host "    - Espere pelo evento EID 2000 no Event Log '$EventLogChannel'" -ForegroundColor Yellow
Write-Host "      (source $EventLogSource) antes de lancar o jogo." -ForegroundColor Yellow
Write-Host "    - EDID em VMs Hyper-V e INERTE (driver sintetico re-le do host)." -ForegroundColor Yellow
Write-Host ""
Write-Host "  Verificar estado:  .\scripts\spoof-persistence-task.ps1 -Show" -ForegroundColor White
Write-Host "  Testar agora:      .\scripts\spoof-persistence-task.ps1 -RunNow" -ForegroundColor White
Write-Host "  Desinstalar:       .\scripts\spoof-persistence-task.ps1 -Uninstall" -ForegroundColor White
Write-Host ""

exit 0
